// deploy.js
// PEUAP-W3 — Full Contract Deployment Script
// Deploys: BiometricVerifier → IdentifierStorage → AuditTrail → AuthenticatorContract
// Network: Sepolia testnet
//
// Usage:
//   npx hardhat run scripts/deploy.js --network sepolia

const hre = require("hardhat");

async function main() {
    const [deployer] = await hre.ethers.getSigners();
    console.log("═══════════════════════════════════════════════════════");
    console.log("  PEUAP-W3 Contract Deployment");
    console.log("  Deployer:", deployer.address);
    console.log("  Network: ", hre.network.name);
    console.log("═══════════════════════════════════════════════════════");

    const balance = await hre.ethers.provider.getBalance(deployer.address);
    console.log("  Balance: ", hre.ethers.formatEther(balance), "ETH\n");

    // ── 1. Deploy BiometricVerifier (auto-generated by snarkjs) ──────────
    console.log("1/4  Deploying BiometricVerifier...");
    const Verifier = await hre.ethers.getContractFactory("contracts/BiometricVerifier.sol:Groth16Verifier");
    const verifier = await Verifier.deploy();
    await verifier.waitForDeployment();
    const verifierAddr = await verifier.getAddress();
    console.log("     ✅ BiometricVerifier:", verifierAddr);

    // ── 2. Deploy IdentifierStorage ───────────────────────────────────────
    console.log("\n2/4  Deploying IdentifierStorage...");
    const IdentifierStorage = await hre.ethers.getContractFactory("IdentifierStorage");
    // Issuer = deployer for now (update to ACA-Py agent address after SSI setup)
    const identifierStorage = await IdentifierStorage.deploy(deployer.address);
    await identifierStorage.waitForDeployment();
    const identifierStorageAddr = await identifierStorage.getAddress();
    console.log("     ✅ IdentifierStorage:", identifierStorageAddr);

    // ── 3. Deploy AuditTrail (2-of-3 threshold for prototype) ────────────
    console.log("\n3/4  Deploying AuditTrail...");
    // For prototype: deployer is all 3 auditors
    // In production: replace with 3 separate auditor addresses
    const auditorAddresses = [
        deployer.address,
        deployer.address,
        deployer.address
    ];
    const requiredVotes = 2; // k = 2 of n = 3

    const AuditTrail = await hre.ethers.getContractFactory("AuditTrail");
    const auditTrail = await AuditTrail.deploy(1, [deployer.address]);
    await auditTrail.waitForDeployment();
    const auditTrailAddr = await auditTrail.getAddress();
    console.log("     ✅ AuditTrail:", auditTrailAddr);
    console.log("        k-of-n: 2-of-1 (prototype — use 3 addresses in production)");

    // ── 4. Deploy AuthenticatorContract ───────────────────────────────────
    console.log("\n4/4  Deploying AuthenticatorContract...");
    const AuthenticatorContract = await hre.ethers.getContractFactory("AuthenticatorContract");
    const authenticator = await AuthenticatorContract.deploy(
        verifierAddr,
        identifierStorageAddr,
        auditTrailAddr
    );
    await authenticator.waitForDeployment();
    const authenticatorAddr = await authenticator.getAddress();
    console.log("     ✅ AuthenticatorContract:", authenticatorAddr);

    // ── 5. Wire up: set AuthenticatorContract address in AuditTrail ───────
    console.log("\n5/5  Wiring contracts...");
    const tx = await auditTrail.setAuthenticatorContract(authenticatorAddr);
    await tx.wait();
    console.log("     ✅ AuditTrail.authenticatorContract =", authenticatorAddr);

    // ── Summary ───────────────────────────────────────────────────────────
    console.log("\n═══════════════════════════════════════════════════════");
    console.log("  DEPLOYMENT COMPLETE");
    console.log("═══════════════════════════════════════════════════════");
    console.log("  BiometricVerifier:      ", verifierAddr);
    console.log("  IdentifierStorage:      ", identifierStorageAddr);
    console.log("  AuditTrail:             ", auditTrailAddr);
    console.log("  AuthenticatorContract:  ", authenticatorAddr);
    console.log("═══════════════════════════════════════════════════════");
    console.log("\n  Add these to your .env file:");
    console.log(`  BIOMETRIC_VERIFIER_ADDRESS=${verifierAddr}`);
    console.log(`  IDENTIFIER_STORAGE_ADDRESS=${identifierStorageAddr}`);
    console.log(`  AUDIT_TRAIL_ADDRESS=${auditTrailAddr}`);
    console.log(`  AUTHENTICATOR_ADDRESS=${authenticatorAddr}`);
    console.log("\n  Verify on Sepolia Etherscan:");
    console.log(`  https://sepolia.etherscan.io/address/${authenticatorAddr}`);
}

main()
    .then(() => process.exit(0))
    .catch((error) => {
        console.error(error);
        process.exit(1);
    });
